name: push only

on:
  push:
    paths:
      - "folder0/folder1/**"
      - ".github/workflows/test.yaml"

defaults:
  run:
    shell: bash

jobs:
  somting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testy"
