name: blabla bacon n eggs

on:
  push:
    paths:
      - "folder0/folder1/**"
      - ".github/workflows/test.yaml"
  pull_request:
    paths:
      - "folder0/folder2/**"
      - ".github/workflows/test.yaml"

defaults:
  run:
    shell: bash

jobs:
  somting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testy"
