name: blabla bacon n eggs
on:
    pull_request:
        branches:
            - basickarl/gh-actions-pr

# on: [pull_request]

defaults:
    run:
        shell: bash

jobs:
    somting:
        runs-on: ubuntu-latest
        steps:
            - run: echo "testy"

# 1.