name: blabla bacon n eggs
on:
    pull_request:
        branches:
            - develop
            - main
on: [pull_request]

defaults:
    run:
        shell: bash

jobs:
    somting:
        runs-on: ubuntu-latest
        steps:
            - run: echo "testy"


